Repository Rathi2000/Dummyy, pull requests merged in 2020-10, with the labels that each got.

#2 Create app.js
  fact/app.js
Labels: hacktoberfest-accepted

#1 Create fact.md
  README.md
  facts/code.js
  facts/fact.md
  facts/loop.c
  facts/main.md
  while.cpp
Labels: hacktoberfest-accepted

#3 Update while.cpp
  while.cpp
Labels: hacktoberfest-accepted

#4 hii
  README.md
  while.cpp
Labels: hactoberfest-accepted

#6 first file
  grade.c
Labels: hacktoberfest-accepted

#8 first file
  c.c
Labels: hacktoberfest-accepted

#7 First File
  fact/3d_array_address.c
Labels: hacktoberfest-accepted

#9 second file
  file_write.c
Labels: hacktoberfest-accepted

#10 second file
  marks.c
Labels: hacktoberfest-accepted

#11 second file
  h.c
Labels: hacktoberfest-accepted

#12 third file
  g.c
Labels: hacktoberfest-accepted

#13 third file
  pointer_arithmetic.c
Labels: hacktoberfest-accepted

#14 third files
  dowhile.c
  function.c
Labels: hacktoberfest-accepted

#15 fourth file
  string_input.c
Labels: hacktoberfest-accepted

#16 fourth file
  aptr.c
Labels: hacktoberfest-accepted

#17 fourth file
  b.c
Labels: hacktoberfest-accepted

#5 Update README.md
  README.md
Labels: hacktoberfest-accepted

#18 Create hello.js
  raja/hello.js
Labels: bug, hacktoberfest-accepted

#19 Create hello.world
  Gaurav/hello.world
Labels: hacktoberfest-accepted

#20 anuj
  Anuj/ab.c
  Anuj/abcd.c
Labels: hacktoberfest-accepted

#21 Create hell.yeah
  Gaurav/hell.yeah
Labels: hacktoberfest-accepted

#22 Create hello.cpp
  raja/hello.cpp
Labels: hacktoberfest-accepted

#23 Create abcfhuh.c
  Anuj/abcfhuh.c
Labels: hacktoberfest-accepted

#24 Create hello.py
  raja/hello.py
Labels: hacktoberfest-accepted

#25 Create ascvf.c
  Anuj/ascvf.c
Labels: hacktoberfest-accepted

#27 Create hgdhj.c
  Anuj/hgdhj.c
Labels: hacktoberfest-accepted

#28 Create subare.reZero
  Gaurav/subare.reZero
Labels: hacktoberfest-accepted

#29 Create hello.c
  raja/hello.c
Labels: hacktoberfest-accepted

#30 Create .cpp
  Adityan/.cpp
Labels: hacktoberfest-accepted

#31 Create adityan.c
  Adityan/adityan.c
Labels: hacktoberfest-accepted

#32 Create hlo.c
  Adityan/hlo.c
Labels: hacktoberfest-accepted

#33 Create abc.c
  Adityan/abc.c
Labels: hacktoberfest-accepted

#34 Create programmer.c
  Akshay/programmer.c
Labels: hactoberfest-accepted

#35 Create hloakshay.c
  hloakshay.c
Labels: hacktoberfest-accepted, hactoberfest-accepted

#36 adityan
  Adityan/adityanhlo.c
  Adityan/adityanhloa.c
  adityan123/xyzabc.c
Labels: hacktoberfest-accepted

#37 Create abcadityan.c
  Adityan/abcadityan.c
Labels: hacktoberfest-accepted

#38 hlogithub.c
  hloakshay2.c
  hloakshay3.c
Labels: hacktoberfest-accepted

#39 Createa abcadityan12.c
  Adityan/abcadityan12.c
Labels: hacktoberfest-accepted

#40 Create abchloa.c
  Adityan/abchloa.c
Labels: hacktoberfest-accepted

#41 Create kjjgjg.c
  Anuj/kjjgjg.c
Labels: hacktoberfest-accepted

#42 Create mnjfjdjh.c
  Anuj/mnjfjdjh.c
Labels: hacktoberfest-accepted

#43 Create Akshay1.c
  Akshay1.c
Labels: hacktoberfest-accepted

#44 Create ldkjfkhfh.c
  Anuj/ldkjfkhfh.c
Labels: hacktoberfest-accepted

#45 Create hloakshay4
  hloakshay4
Labels: hacktoberfest-accepted

#46 Create pojdjejhdhf.c
  Anuj/pojdjejhdhf.c
Labels: hacktoberfest-accepted

#47 Create adityan12345.c
  adityan123.cpp/adityan12345.c
Labels: hacktoberfest-accepted

#48 Create kjfkdsfhdshgkdkfgh.c
  Anuj/kjfkdsfhdshgkdkfgh.c
Labels: hacktoberfest-accepted

#49 Create shdfcsdkfksdhcsdksgiyfdg.c
  Anuj/shdfcsdkfksdhcsdksgiyfdg.c
Labels: hacktoberfest-accepted

#50 Createa ghij.c
  adityan123.cpp/ghij.c
Labels: hacktoberfest-accepted

#51 Create fhrifuerherhigerlgrhdgiregrehg.c
  Anuj/fhrifuerherhigerlgrhdgiregrehg.c
Labels: hacktoberfest-accepted

#52 fjhrijfrk
  Anuj/ifbbvhdfgfhdbrdygrydgiyo.c
  Anuj/ihfrehbgoildfbghitrgthr.c
Labels: hacktoberfest-accepted

#53 xdhCreate ihjgfx.c
  adityan123.cpp/ihjgfx.c
Labels: hacktoberfest-accepted

#54 igfCreate ilhg.c
  adityan123.cpp/ilhg.c
Labels: hacktoberfest-accepted
